# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Triplebit Development Corporation
tagline:          'Privacy-Friendly Internet Services'
description:      'The Triplebit Development Corporation offers privacy-friendly hosting services to select organizations.'
url:              https://www.triplebit.dev

author:
  name:           'Jonah Aragon'
  url:            https://twitter.com/jonaharagon

paginate:         5
paginate_path:    '/blog/page:num/'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/triplebit

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
